import Head from "next/head";
import {
  Container,
  SimpleGrid,
  Heading,
  Text,
  Flex,
  Spacer,
  Badge,
  Box,
  Progress,
  Stack,
  chakra,
} from "@chakra-ui/react";

import { Sidebar } from "../../components/Sidebar/index.jsx";

const assignments = [
  {
    name: "Turn in forms",
    description: "You need to turn in your forms for the next week.",
    status: "Completed",
  },
  {
    name: "Review robot basics",
    description: "You need to review the basics of the robot.",
    status: "In progress",
  },
  {
    name: "Attend kickoff session",
    description: "You need to attend the kickoff session.",
    status: "Not started",
  },
];

const colors = {
  "Not started": "red",
  "In progress": "yellow",
  Completed: "green",
};
export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Dashboard - RoboReach</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar active="dashboard">
        <Container maxW="container.2xl" mt="8">
          <Heading as="h1" size="2xl" color="text.dark">
            Welcome back, <chakra.span color="green.dark">John</chakra.span>.
          </Heading>

          <Heading as="h1" size="2xl" color="green.dark" mt="8">
            Congratulations! You’ve been accepted into Challenge Build.
          </Heading>

          <Box mt={8}>
            <Text fontSize="xl" color="text.dark">
              Progress through{" "}
              <chakra.span color="green.dark" fontWeight="bold">
                Challenge Build
              </chakra.span>{" "}
              program:
              <chakra.span color="green.dark" fontWeight="bold">
                {" "}
                0/8 weeks competed.
              </chakra.span>
            </Text>
            <Progress
              mt={2}
              rounded="md"
              colorScheme="green"
              size="lg"
              value={5}
              maxW="500px"
            />
          </Box>

          <SimpleGrid columns={{ base: 1, md: 2 }} spacing={0} mt={8}>
            <Box>
              <Text fontSize="xl" color="green.dark">
                Your assignments:
              </Text>
              <Stack direction="column" spacing={4} mt={2}>
                {assignments.map((assignment) => (
                  <Flex
                    bg="white"
                    p={2}
                    rounded="md"
                    shadow="md"
                    maxW="500px"
                    align="center"
                  >
                    <Box>
                      <Text fontWeight="bold">{assignment.name}</Text>
                      <Text color="gray.600" fontSize="sm">
                        {assignment.description}
                      </Text>
                    </Box>
                    <Spacer />
                    <Badge
                      fontSize="sm"
                      colorScheme={colors[assignment.status]}
                    >
                      {assignment.status}
                    </Badge>
                  </Flex>
                ))}
              </Stack>
            </Box>

            <Box maxW="500px">
              <Text fontSize="xl" color="green.dark">
                Your program dates:
              </Text>
              <Box bg="white" p={2} rounded="md" shadow="md">
                <Text fontSize="xl" color="text.dark" fontWeight="bold">
                  Meetings:
                </Text>
                <Text>Tuesdays, Thursdays, Saturdays: 5PM-9PM</Text>

                <Text fontSize="xl" color="text.dark" fontWeight="bold" mt={4}>
                  Overall Dates:
                </Text>
                <Text>Academic Year Spring (2203, Jan 23 - Mar 24)</Text>
              </Box>
            </Box>
          </SimpleGrid>
        </Container>
      </Sidebar>
    </>
  );
}
