import Head from "next/head";
import {
  Container,
  SimpleGrid,
  Heading,
  Text,
  WrapItem,
  Avatar,
  Flex,
  Spacer,
  Badge,
  Box,
  Icon,
  Progress,
  Stack,
  chakra,
} from "@chakra-ui/react";
import { FiPhone } from "react-icons/fi";
import { AiOutlineMail } from "react-icons/ai";
import { BsCameraVideoFill } from "react-icons/bs";
import { Sidebar } from "../../components/Sidebar/index.jsx";

export default function MentorDashboard() {
  return (
    <>
      <Head>
        <title>Mentor | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar active="mentor contact">
        <Container maxW="container.2xl" mt="8">
          <Box d="flex" alignItems="center">
            <Heading as="h1" size="2xl" color="text.dark">
              Your Mentor is:{" "}
              <chakra.span color="green.dark">Jane Doe</chakra.span>
            </Heading>
            <WrapItem ml={4}>
              <Avatar size="xl" name="Segun Adebayo" src="/jane.jpeg" />{" "}
            </WrapItem>
          </Box>

          <Box bg="white" p={4} rounded="md" shadow="md" mt={2}>
            <Text color="green.dark" fontWeight="bold" fontSize="xl">
              Mentor Bio
            </Text>
            <Text>
              Hi there! I'm Jane, a machine learning software engineer at Apple.
              Since discovering programming in 7th grade, coding has fascinated
              me with how simple, yet complex it is. In my free time, I like to
              create applications that have a positive impact on the lives of
              those around me. I've created Chrome extensions, mobile apps,
              websites for non-profits, and machine learning models. Currently,
              I'm working on an app that helps users track expiration dates for
              products!
            </Text>

            <Stack direction="column" mt="4">
              <Box d="flex" alignItems="center">
                <Icon as={FiPhone} fontSize="2xl" color="green.dark" />
                <Text fontSize="xl" color="text.dark" ml={2}>
                  (123) 456-7890
                </Text>
              </Box>
              <Box d="flex" alignItems="center">
                <Icon as={AiOutlineMail} fontSize="2xl" color="green.dark" />
                <Text fontSize="xl" color="text.dark" ml={2}>
                  jane@doe.com
                </Text>
              </Box>
              <Box d="flex" alignItems="center">
                <Icon
                  as={BsCameraVideoFill}
                  fontSize="2xl"
                  color="green.dark"
                />
                <Text fontSize="xl" color="text.dark" ml={2}>
                  janedoe.zoom.us/samplemeeting
                </Text>
              </Box>
            </Stack>
          </Box>
        </Container>
      </Sidebar>
    </>
  );
}
