import Head from 'next/head'
import { NavBar } from '../components/NavBar/index.tsx'
import { Footer } from '../components/Footer/index.tsx'
import { LeftTextWithButton } from '../components/TwoCol/LeftTextWithButton'
import { Container } from '@chakra-ui/react'
import { MedSep } from '../components/Separators/MedSep'
import { CardDisplay } from '../components/ThreeCol/CardDisplay'
import { HeadingWithDesc } from '../components/Headings/HeadingWithDesc'
import { MedSepNoLine } from '../components/Separators/MedSepNoLine'
import { TwoColWithPic } from '../components/Landing/TwoColWithPic'
import { TwoColTextWithPic } from '../components/TwoCol/TwoColTextWithPic'
import { SubSection } from '../components/OneCol/SubSection'
import Serve from '../data/whoWeServe.json'
import Fade from 'react-reveal/Fade';
import { TeamGrid } from '../components/ThreeCol/TeamGrid'
export default function Home() {
    return (
        <>
            <Head>
                <title>About - RoboReach</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <NavBar active="about" />

            <Container maxW="container.xl" mt="8">
                <Fade>
                    <TwoColWithPic
                        pic='/about.jpeg'
                        title="About Us"
                        desc="RoboReach is a non-profit organization that uses robotics to build the leaders of tomorrow. We are fostering a community of youth who are passionate about creating a better future for themselves and their communities."
                        button1="Learn More"
                        link1="#subsection"
                        button2="Sign Up"
                        link2="/apply"
                        radius="md"
                    />

                    <MedSep />

                    <TwoColTextWithPic
                        title="Our Mission"
                        desc="For no cost, underprivileged students around the nation are provided with remote STEM opportunities focused in robotics. In these programs, students not only gain a foundation in key STEM principles but also advanced skills that give them an academic and professional edge. 
                        "
                        buttonText="Learn More"
                        buttonLink="/about"
                        pic="/hand.jpeg"
                        radius="md"
                        align='right'
                        color='blue.light'
                        hoverColor='blue.dark'

                    />
                    <MedSep />
                    <SubSection
                        title="Our Story"
                        desc="With the start of the coronavirus and all schools being shut down, we found that students were lacking continual learning stimulation over the summer with the loss of in person opportunities. Starting RoboReach, we aimed to create a program to fill this hole and provide STEM inspiration and opportunities to students. We strive to continue these efforts through and after the coronavirus pandemic in order to bridge accessibility and overcome the poverty gap. "
                    />
                    <MedSep />
                    <LeftTextWithButton
                        title="Our Vision"
                        desc="Using a remote format, we seek to use technology to increase accessibility and awareness of STEM in these communities, reaching demographics that are lacking not only representation in STEM fields but general educational resources as well. We envision our organization expanding to bridge technology gaps not only locally but globally as well. "
                        button="Learn More"
                        buttonLink="/about"
                        image="/temp_vision.png"
                        radius="md"
                    />
                    <MedSep />
                    <HeadingWithDesc desc="All of our programs are free and virtual!">Who We Serve</HeadingWithDesc>

                    <CardDisplay
                        data={Serve}
                    />

                    <MedSep />
                    <HeadingWithDesc desc="All of our programs are free and virtual!">Our Team </HeadingWithDesc>
                    <TeamGrid />





                    <MedSepNoLine />


                    <Footer />
                </Fade>
            </Container>


        </>
    )
}
