import Head from 'next/head'
import { NavBar } from '../components/NavBar/index.tsx'
import { Footer } from '../components/Footer/index.tsx'
import { LeftTextWithButton } from '../components/TwoCol/LeftTextWithButton'
import { Container } from '@chakra-ui/react'
import { MedSep } from '../components/Separators/MedSep'
import { CardDisplay } from '../components/ThreeCol/CardDisplay'
import { HeadingWithDesc } from '../components/Headings/HeadingWithDesc'
import { MedSepNoLine } from '../components/Separators/MedSepNoLine'
import { TwoColWithPic } from '../components/Landing/TwoColWithPic'
import { SubSection } from '../components/OneCol/SubSection'
import Serve from '../data/whoWeServe.json'
import Fade from 'react-reveal/Fade';
import { TeamGrid } from '../components/ThreeCol/TeamGrid'
export default function Home() {
    return (
        <>
            <Head>
                <title>About - RoboReach</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <NavBar active="about" />

            <Container maxW="container.xl" mt="8">
                <Fade>
                    <TwoColWithPic
                        pic='/temp_first.png'
                        title="About Us"
                        desc="RoboReach is a non-profit organization that uses robotics to build the leaders of tomorrow. We are building a community of young people who are passionate about building a better future for themselves and their communities."
                        button1="Learn More"
                        link1="/about"
                        button2="Sign Up"
                        link2="/apply"
                    />

                    <MedSep />

                    <LeftTextWithButton
                        title="Our Mission"
                        desc="RoboReach is a non-profit organization that uses robotics to build the leaders of tomorrow. We are building a community of young people who are passionate about building a better future for themselves and their communities."
                        button="Learn More"
                        buttonLink="/about"
                        image="/temp_playing.png"
                        radius="md"
                    />
                    <MedSep />
                    <SubSection
                        title="Our Story"
                        desc="While thinking about how to win TSA, we came up with a grand idea of RoboReach. I really like making up things to type instead of using lorem ipsum haha. While thinking about how to win TSA, we came up with a grand idea of RoboReach. I really like making up things to type instead of using lorem ipsum haha."
                    />
                    <MedSep />
                    <LeftTextWithButton
                        title="Our Vision"
                        desc="Within the next 10 years, we hope to exapnd into a global market, providing students in not only the United States with a fun, quality education. We hope to do this by sucking dick and making sure that we have a brain instead of being brain dead. If your interests align with ours, please don’t hesitate to sign to be a mentor!"
                        button="Learn More"
                        buttonLink="/about"
                        image="/temp_vision.png"
                        radius="md"
                    />
                    <MedSep />
                    <HeadingWithDesc desc="All of our programs are free and virtual!">Who We Serve</HeadingWithDesc>

                    <CardDisplay
                        data={Serve}
                    />

                    <MedSep />
                    <HeadingWithDesc desc="All of our programs are free and virtual!">Our Team </HeadingWithDesc>
                    <TeamGrid />





                    <MedSepNoLine />


                    <Footer />
                </Fade>
            </Container>


        </>
    )
}
