import Head from 'next/head'
import { Navbar } from '../components/Navbar'
import { Footer } from '../components/Footer'
import { Landing } from '../components/Landing'
import { Application } from '../components/Application'
import { MedSep } from '../components/Separators/MedSep'
export default function Login() {
    return (
        <>
            <Head>
                <title>Login - RoboReach</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />

            <Landing
                title="Student Application"
                desc="Apply to join our free program!"
            />

            <MedSep />
            <div className="container mx-auto px-4">

                <Application />

                <MedSep />

                <MedSep />
            </div>

            {/* <Footer /> */}

        </>
    )
}
