import Head from 'next/head'
import { NavBar } from '../components/NavBar/index.tsx'
import { Footer } from '../components/Footer/index.tsx'
import { Container, SimpleGrid } from '@chakra-ui/react'
import { MedSep } from '../components/Separators/MedSep'
import { HeadingWithDesc } from '../components/Headings/HeadingWithDesc'
import { MedSepNoLine } from '../components/Separators/MedSepNoLine'
import { TwoColWithPic } from '../components/Landing/TwoColWithPic'
import Fade from 'react-reveal/Fade';
import { FullTabs } from '../components/FullPage/FullTabs'
import Data from '../data/builds.json'

export default function Builds({ posts }) {
    return (
        <>
            <Head>
                <title>Builds - RoboReach</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <NavBar active="programs" />

            <Container maxW="container.xl" mt="8">
                <Fade>
                    <TwoColWithPic
                        pic='/prog.jpeg'
                        title="Our Programs"
                        desc="All of our 3 programs are free!"
                        radius="md"
                        button1="Apply Now"
                        link1="/apply"
                        align="left"
                    />

                    <MedSep />

                    <FullTabs
                        data={Data}
                    />






                    <MedSepNoLine />
                    <Footer />
                </Fade>
            </Container>


        </>
    )
}