import Head from 'next/head'
import { NavBar } from '../components/NavBar/index.tsx'
import { Footer } from '../components/Footer/index.tsx'
import { Container } from '@chakra-ui/react'
import { MedSep } from '../components/Separators/MedSep'
import Fade from 'react-reveal/Fade';
import Data from '../data/faq.json'
// import { CollapseData } from '../components/OneCol/CollapseData'
import { QandA } from '../components/ThreeCol/QandA'
import { OnlyTextWithButton } from '../components/Landing/OnlyTextWithButton'

export default function Builds({ posts }) {
    return (
        <>
            <Head>
                <title>Builds - RoboReach</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <NavBar active="application" />

            <Container maxW="container.xl" mt="8">
                <Fade>
                    <OnlyTextWithButton
                        title="Frequently Asked Questions"
                        desc="Here you can find answers to the most common questions about our programs."
                        buttonText="Still have questions?"
                        buttonLink="mailto:teamroboreach@gmail.com"
                    />

                    <MedSep />

                    {/* <CollapseData data={Data} /> */}
                    <QandA data={Data} />
                    <MedSep />
                    <Footer />
                </Fade>
            </Container>


        </>
    )
}