import Head from 'next/head'
import { NavBar } from '../components/NavBar/index.tsx'
import { Footer } from '../components/Footer/index.tsx'
import { Container, SimpleGrid } from '@chakra-ui/react'
import { MedSep } from '../components/Separators/MedSep'
import { HeadingWithDesc } from '../components/Headings/HeadingWithDesc'
import { MedSepNoLine } from '../components/Separators/MedSepNoLine'
import { TwoColWithPic } from '../components/Landing/TwoColWithPic'
import Fade from 'react-reveal/Fade';
import React, { useState } from 'react'
import { TriColCounter } from '../components/ThreeCol/TriColCounter'
import byNumbers from '../data/byNumbers.json'
import { ChartDualCol } from '../components/ThreeCol/ChartDualCol'
import { BlogCard } from '../components/Blog/BlogCard'
import { getAllFilesFrontMatter } from '../lib/mdx'
export default function Impact({ posts }) {
    const [searchValue, setSearchValue] = useState('')
    let filteredBlogPosts = posts
        .sort(
            (a, b) =>
                Number(new Date(a.publishedAt)) - Number(new Date(b.publishedAt))
        )
        .filter((frontMatter) =>
            frontMatter.title?.toLowerCase()?.includes(searchValue.toLowerCase()) ||
            frontMatter.summary?.toLowerCase()?.includes(searchValue.toLowerCase())
        )

    return (
        <>
            <Head>
                <title>Impact - RoboReach</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <NavBar active="programs" />

            <Container maxW="container.xl" mt="8">
                <Fade>
                    <TwoColWithPic
                        pic='/impact.jpeg'
                        title="Our Impact"
                        desc="RoboReach is a non-profit organization that uses robotics to build the leaders of tomorrow. We are building a community of young people who are passionate about building a better future for themselves and their communities."
                        button1="Our Blog"
                        link1="#blog"
                        align="left"
                        radius='md'
                    />

                    <MedSep />

                    <HeadingWithDesc>By the Numbers</HeadingWithDesc>
                    <TriColCounter
                        data={byNumbers}
                    />

                    <MedSep />
                    <ChartDualCol />

                    <MedSep />

                    <HeadingWithDesc>Read our Blog</HeadingWithDesc>

                    <SimpleGrid columns={{ base: 1, md: 2, lg: 3 }} spacing={8} id="blog">
                        {filteredBlogPosts.map((frontMatter) => (
                            <BlogCard
                                key={frontMatter.title}
                                title={frontMatter.title}
                                slug={frontMatter.slug}
                                image={frontMatter.image}
                                desc={frontMatter.summary}
                                readingTime={frontMatter.readingTime}
                                link={`blog/${frontMatter.slug}`}
                                publishedAt={frontMatter.publishedAt}
                                isTrunc={true}
                            />
                        ))}
                    </SimpleGrid>


                    <MedSepNoLine />
                    <Footer />
                </Fade>
            </Container>


        </>
    )
}

export async function getStaticProps() {

    const categories = ['blog'];
    const finalPosts = [];

    for (var i = 0; i < categories.length; i++) {
        const retrievedPosts = await getAllFilesFrontMatter(categories[i])

        finalPosts.push(...retrievedPosts)
    }
    return { props: { posts: finalPosts } }
}