import Head from 'next/head'
import { Landing } from '../components/Landing'
import { LeftTextWithButton } from '../components/TwoCol/LeftTextWithButton'
import { MedSep } from '../components/Separators/MedSep'
import { SmallSep } from '../components/Separators/SmallSep'
import Benefits from '../data/benefits.json'
import { TriColCards } from '../components/Displays/TriColCards'
import { Heading } from '../components/Text/Heading'
import { RightTextWithButtonBuild } from '../components/TwoCol/RightTextWithButtonBuild'
import { LeftTextWithButtonBuild } from '../components/TwoCol/LeftTextWithButtonBuild'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <Landing
        title="RoboReach"
        desc="Using robotics to build the leaders of tomorrow"
        button1="Sign Up"
        link1="/signup"
      />
      <MedSep />
      <div className="container mx-auto px-4">
        <LeftTextWithButton
          title="The Future of Education"
          desc="For no cost, underprivileged students around the nation are provided with remote stem opportunities focused in robotics. In these programs, students not only gain a foundation in key STEM principles but also advanced skills that give them an academic and professional edge.  Under strict rules and limited time and resources, teams of high school students are challenged to build industrial-size."
          buttonText="Learn More"
          buttonLink="/about"
          pic="/first.png"
        />

        <MedSep />

        <Heading desc="All of our programs are free and virtual!">Benefits</Heading>
        <TriColCards
          data={Benefits}
        />

        <MedSep />
        <Heading desc="Join us as we build robots!">Robot Builds</Heading>
        <RightTextWithButtonBuild
          title="Common Build"
          desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley. "
          buttonText="Learn More"
          buttonLink="/TODO"
          keyword="Ages:"
          answer="K-3"
          pic="/common.png"
          color="dark-green"
          colorHover="darker-green"
        />
        <SmallSep />
        <LeftTextWithButtonBuild
          title="Challenge Build"
          desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley. "
          buttonText="Learn More"
          buttonLink="/TODO"
          keyword="Ages:"
          answer="4-7"
          pic="/challenge.png"
          color="light-blue"
          colorHover="dark-blue"
        />
        <SmallSep />

        <RightTextWithButtonBuild
          title="Creative Build"
          desc="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley. "
          buttonText="Learn More"
          buttonLink="/TODO"
          keyword="Ages:"
          answer="8-12"
          pic="/creative.png"
          color="dark-blue"
          colorHover="darker-blue"
        />

        <MedSep />
      </div>


    </>
  )
}
