import Head from 'next/head'
import { Landing } from '../components/Landing'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <Landing
        title="RoboReach"
        desc="Using robotics to build the leaders of tomorrow"
        button1="Sign Up"
        link1="/signup"
      />
    </>
  )
}
