import Head from 'next/head'
import { Navbar } from '../components/Navbar'
import { LoginTwoCol } from '../components/TwoCol/LoginTwoCol'
export default function Login() {
    return (
        <>
            <Head>
                <title>Login - RoboReach</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />

            <LoginTwoCol />

        </>
    )
}
