import Head from 'next/head'
import { Navbar } from '../components/Navbar'
import { SignupTwoCol } from '../components/TwoCol/SignupTwoCol'
export default function Signup() {
    return (
        <>
            <Head>
                <title>Signup - RoboReach</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />

            <SignupTwoCol />



        </>
    )
}
